---
resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/95rade/flight-school
    branch: master

- name: flight-school-docker-image
  type: docker-image
  source:
    repository: rade95/flight-school-example    # dockerhub.com/rade95
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}

jobs:
- name: build-cached-image
  plan:
  - get: flight-school
  - task: build-cached-image-workspace
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          #repository: ubuntu
          repository: ruby
      outputs:
      - name: workspace    # creates directory workspace and copies flight-school repo into it
      inputs:
      - name: flight-school # input dir is the repo
      run:
        path: /bin/bash
        args:
        - -c
        - |
          output_dir=workspace
          pwd
          uname -a
          cat << EOF > "${output_dir}/Dockerfile"
          FROM ruby

          ADD flight-school /tmp/flight-school
          RUN bundle install --gemfile=/tmp/flight-school/Gemfile
          ##RUN rm -rf /tmp/flight-school
          EOF

          cp -R ./flight-school "${output_dir}/flight-school"  # copies repo dir 'flight-school' into image 'workspace'

  - put: flight-school-docker-image   # this is the output - docker-image
    params:
      build: workspace

- name: test-it!
  plan:
  - get: flight-school-docker-image
    passed: [build-cached-image]
    trigger: true
  - get: flight-school
    passed: [build-cached-image]
  - task: run-tests
    image: flight-school-docker-image  # task runs inside image container
    config:
      platform: linux
      inputs:
      - name: flight-school
      run:
        path: ./flight-school/ci/test.sh
        #path: ci/test.sh
      #run:
      #  dir: flight-school
      #  path: bundle
      #  args:
      #  - exec
      #  - rspec
